function(ztk_add_test name)
    add_executable(${name} ${name}.c)
    target_link_libraries(${name} PRIVATE ztk)
    add_test(NAME ${name} COMMAND ${name})
endfunction()

ztk_add_test(test_platform)
ztk_add_test(test_byte_buf)
ztk_add_test(test_buf)
ztk_add_test(test_mpsc)
ztk_add_test(test_sync)
ztk_add_test(test_thread_pool)

if (ZTK_HAVE_OPENSSL AND (ZTK_HAVE_EPOLL OR ZTK_HAVE_WEPOLL))
    add_executable(test_ssl test_ssl.c)
    target_link_libraries(test_ssl PRIVATE ztk)
    target_compile_definitions(test_ssl PRIVATE ZTK_HAVE_OPENSSL=1)
    add_test(NAME test_ssl COMMAND test_ssl)
endif ()

if (ZTK_HAVE_EPOLL OR ZTK_HAVE_WEPOLL)
    ztk_add_test(test_poller)
    ztk_add_test(test_socket)
    ztk_add_test(test_tcp_server)
    ztk_add_test(test_tcp_sendv)
    add_executable(test_tcp_send_buf_bench test_tcp_send_buf_bench.c)
    target_link_libraries(test_tcp_send_buf_bench PRIVATE ztk)
    target_compile_definitions(test_tcp_send_buf_bench PRIVATE ZTK_TEST_HOOKS=1)
    target_compile_definitions(ztk PRIVATE ZTK_TEST_HOOKS=1)
    add_test(NAME test_tcp_send_buf_bench COMMAND test_tcp_send_buf_bench)
    ztk_add_test(test_bbr)
    ztk_add_test(test_poller_async)
    ztk_add_test(test_timer)
    ztk_add_test(test_timer_load)
    ztk_add_test(test_poller_pool)
    ztk_add_test(test_net_extended)
    ztk_add_test(test_rtp_port)
endif ()
